# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

bundle: clean
	zip automation_bundle.zip watch-gs-* sdr-contact-completed.sh stop-instance.sh

clean:
	rm -f automation_bundle.zip